/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Format
 */
export interface Format {
    /**
     * 
     * @type {number}
     * @memberof Format
     */
    bmltId: number;
    /**
     * 
     * @type {string}
     * @memberof Format
     */
    keyString: string;
    /**
     * 
     * @type {string}
     * @memberof Format
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Format
     */
    worldId: string;
    /**
     * 
     * @type {string}
     * @memberof Format
     */
    nawsCodeOverride: string;
}

/**
 * Check if a given object implements the Format interface.
 */
export function instanceOfFormat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bmltId" in value;
    isInstance = isInstance && "keyString" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "worldId" in value;
    isInstance = isInstance && "nawsCodeOverride" in value;

    return isInstance;
}

export function FormatFromJSON(json: any): Format {
    return FormatFromJSONTyped(json, false);
}

export function FormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Format {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bmltId': json['bmlt_id'],
        'keyString': json['key_string'],
        'name': json['name'],
        'worldId': json['world_id'],
        'nawsCodeOverride': json['naws_code_override'],
    };
}

export function FormatToJSON(value?: Format | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bmlt_id': value.bmltId,
        'key_string': value.keyString,
        'name': value.name,
        'world_id': value.worldId,
        'naws_code_override': value.nawsCodeOverride,
    };
}

