/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const MeetingEventType = {
    MeetingDeleted: 'MeetingDeleted',
    MeetingCreated: 'MeetingCreated',
    MeetingUpdated: 'MeetingUpdated'
} as const;
export type MeetingEventType = typeof MeetingEventType[keyof typeof MeetingEventType];


export function MeetingEventTypeFromJSON(json: any): MeetingEventType {
    return MeetingEventTypeFromJSONTyped(json, false);
}

export function MeetingEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingEventType {
    return json as MeetingEventType;
}

export function MeetingEventTypeToJSON(value?: MeetingEventType | null): any {
    return value as any;
}

