/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NawsCode
 */
export interface NawsCode {
    /**
     * 
     * @type {number}
     * @memberof NawsCode
     */
    bmltId: number;
    /**
     * 
     * @type {string}
     * @memberof NawsCode
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof NawsCode
     */
    rootServerId: number;
}

/**
 * Check if a given object implements the NawsCode interface.
 */
export function instanceOfNawsCode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bmltId" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "rootServerId" in value;

    return isInstance;
}

export function NawsCodeFromJSON(json: any): NawsCode {
    return NawsCodeFromJSONTyped(json, false);
}

export function NawsCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NawsCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bmltId': json['bmlt_id'],
        'code': json['code'],
        'rootServerId': json['root_server_id'],
    };
}

export function NawsCodeToJSON(value?: NawsCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bmlt_id': value.bmltId,
        'code': value.code,
        'root_server_id': value.rootServerId,
    };
}

