/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NawsCodeCreate
 */
export interface NawsCodeCreate {
    /**
     * 
     * @type {number}
     * @memberof NawsCodeCreate
     */
    bmltId: number;
    /**
     * 
     * @type {string}
     * @memberof NawsCodeCreate
     */
    code: string;
}

/**
 * Check if a given object implements the NawsCodeCreate interface.
 */
export function instanceOfNawsCodeCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bmltId" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function NawsCodeCreateFromJSON(json: any): NawsCodeCreate {
    return NawsCodeCreateFromJSONTyped(json, false);
}

export function NawsCodeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NawsCodeCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bmltId': json['bmlt_id'],
        'code': json['code'],
    };
}

export function NawsCodeCreateToJSON(value?: NawsCodeCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bmlt_id': value.bmltId,
        'code': value.code,
    };
}

