/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootServerUpdate
 */
export interface RootServerUpdate {
    /**
     * 
     * @type {string}
     * @memberof RootServerUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RootServerUpdate
     */
    url?: string;
}

/**
 * Check if a given object implements the RootServerUpdate interface.
 */
export function instanceOfRootServerUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RootServerUpdateFromJSON(json: any): RootServerUpdate {
    return RootServerUpdateFromJSONTyped(json, false);
}

export function RootServerUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootServerUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function RootServerUpdateToJSON(value?: RootServerUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

