/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {number}
     * @memberof Snapshot
     */
    rootServerId: number;
    /**
     * 
     * @type {Date}
     * @memberof Snapshot
     */
    date: Date;
}

/**
 * Check if a given object implements the Snapshot interface.
 */
export function instanceOfSnapshot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rootServerId" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rootServerId': json['root_server_id'],
        'date': (new Date(json['date'])),
    };
}

export function SnapshotToJSON(value?: Snapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'root_server_id': value.rootServerId,
        'date': (value.date.toISOString().substr(0,10)),
    };
}

